language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# install required system libraries
before_install:
  - sudo apt-get update --fix-missing -qq
  - sudo apt-get build-dep python-scipy -qq
# command to install dependencies from source
# note, separating requirements so that travis
# will get output in less than 5 min and won't
# terminate, using q to keep build info to a
# minumum for dependencies
install:
  - pip install -q scipy

# command to run tests
script: python runtests.py
